name: ğŸš€ Deploy to Shared Hosting

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  web-deploy:
    name: ğŸ‰ Deploy to disfo.successmandiri.com
    runs-on: ubuntu-latest

    steps:
      # STEP 1: Ambil kode terbaru
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4

      # STEP 2: Setup Node.js untuk build assets
      - name: ğŸ“‚ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      # STEP 3: Build frontend assets
      - name: ğŸ—ï¸ Build Project
        run: |
          npm install
          npm run build
      # STEP 4: Persiapan aplikasi
      - name: ğŸ”§ Prepare Application
        run: |
          cp .env.example .env
          sed -i "s|APP_ENV=.*|APP_ENV=production|" .env
          sed -i "s|APP_DEBUG=.*|APP_DEBUG=false|" .env
          sed -i "s|APP_URL=.*|APP_URL=https://display.successmandiri.com|" .env
      # STEP 5: Deploy ke hosting
      - name: ğŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.successmandiri.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # server-dir: /disfo.successmandiri.com/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/tests/**
            **/.env*
            **/.editorconfig
            **/.styleci.yml
            **/phpunit.xml
            **/README.md
            # **/composer.json
            # **/composer.lock
            # **/package.json
            # **/package-lock.json
            # **/vite.config.js
            **/.github/**
            **/.idea/**
            **/.vscode/**
            # **/storage/*.key
            # **/storage/framework/cache/*
            **/storage/framework/sessions/*
            # **/storage/framework/views/*
